name: Build LaTeX document
on: 
  push:
    paths: 
    - "**/*.tex"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          pre_compile: "chmod +x ./compile_tex.sh"
      - name: Compile LaTeX document
        run: ./compile_tex.sh
      - name: Add file
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Added PDF file'
          add: "*.pdf"
          push: -f
