name: Build LaTeX document
on: 
  push:
    paths: 
    - "**/*.tex"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Get changed .tex files
        id: getfile
        run: |
          echo "::set-output name=file::$(git diff --name-only HEAD~ HEAD | grep .tex | xargs)"
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ steps.getfile.outputs.file }}
          glob_root_file: true
          work_in_root_file_dir: true
      - name: Add file
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Added PDF file'
          add: "*.pdf"
          push: -f
