name: Build LaTeX document
on: 
  push:
    paths: 
    - "**/*.tex"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed .tex files
        id: getfile
        run: |
          file=$(git diff --name-only HEAD~ HEAD | grep .tex | xargs)
          file=${file// /\\ }
          echo "file=$file" >> $GITHUB_ENV
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        if: env.file != ''
        with:
          root_file: ${{ env.file }}
          glob_root_file: true
          work_in_root_file_dir: true
      - name: Add file
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Added PDF file'
          add: "*.pdf"
          push: -f
