name: Build LaTeX document
on: 
  push:
    paths: 
    - 'Open Problems/OpenProblemTemplatev2.tex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 'Open Problems/OpenProblemTemplatev2.tex'
          glob_root_file: true
          work_in_root_file_dir: true
      - name: Add file
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Added PDF file'
          add: "*.pdf"
          push: -f

name: Debug: List workspace contents
  run: ls -R
